---
title: "Bike Sharing Demand Prediction"
date: "`r Sys.Date()`"
output:
    html_document:
        highlight: pygments
        css: ~/Google Drive/ML Lecture/rmarkdown.css
---


```{r knitr_init, echo=FALSE, cache=FALSE, message = FALSE}
library(knitr)
library(rmdformats)
library(ggplot2)
library(dplyr)
library(ggthemr)

knitr::opts_chunk$set(echo = TRUE, message = FALSE, prompt = FALSE,
                      tidy = FALSE, comment = NA, warning = FALSE,
                      fig.height = 5, fig.width = 8, fig.retina = 2,
                      fig.align = "center")

custom_theme <- theme_bw(base_family = "Open Sans") +
    theme(axis.title.x = element_text(size = 11,
                                      margin = margin(10, 0, 0, 0),
                                      face = "bold"),
          axis.title.y = element_text(size = 11,
                                      margin = margin(0, 10, 0, 0),
                                      face = "bold"),
          plot.title = element_text(family = "Open Sans"),
          panel.background = element_blank(),
          axis.text.x = element_text(angle = 90, face = "italic"),
          axis.text.y = element_text(face = "italic"), legend.position = "bottom",
          legend.title = element_text(size = 9, face = 'bold.italic'))
theme_set(custom_theme)
```

# Data Import

```{r, message = FALSE}
library(readr)
library(dplyr)

train <- read_csv("data/bike_train.csv")
test <- read_csv("data/bike_test.csv")
```

```{r}
str(train)
```

```{r}
str(test)
```

```{r}
summary(train)
```

```{r}
summary(test)
```


# Data Handling

```{r}
library(lubridate)

featureExtract <- function(data){
    data <- data %>%
        mutate(year = year(datetime), month = month(datetime), hour = hour(datetime),
               weekdays = weekdays(datetime)) %>%
        mutate(spring = ifelse(season == 1, 1, 0),
               summer = ifelse(season == 2, 1, 0),
               fall = ifelse(season == 3, 1, 0),
               winter = ifelse(season == 4, 1, 0)) %>%
        mutate(weatherGreat = ifelse(weathersit == 1, 1, 0),
               weatherNice = ifelse(weathersit == 2, 1, 0),
               weatherBad = ifelse(weathersit == 3, 1, 0),
               weatherWorst = ifelse(weathersit == 4, 1, 0))
}

train <- featureExtract(train)
test <- featureExtract(test)

head(train)
```

```{r}
head(test)
```

# EDA

```{r}
library(reshape2)
train %>%
    group_by(weekdays) %>%
    summarise(casual = sum(casual), registered = sum(registered)) %>%
    melt(id.vars = "weekdays", variable.name = "type", value.name = "rent") %>%
    mutate(weekdays = ordered(weekdays, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))) %>%
    ggplot(aes(x = weekdays, y = rent, fill = type)) +
    geom_col(position = "dodge")
```


```{r}
train %>%
    group_by(year, month, weathersit) %>%
    summarise(Count = sum(cnt)) %>%
    ggplot(aes(x = factor(month), y = Count, fill = factor(weathersit))) + 
    geom_bar(stat = "identity", position = "dodge") +
    xlab("Month") + scale_fill_discrete(name = "Weather Condition")
```

```{r}
train %>%
    group_by(year, season, weathersit) %>%
    summarise(Count = sum(cnt)) %>%
    ggplot(aes(x = factor(season), y = Count, fill = factor(weathersit))) + 
    geom_bar(stat = "identity", position = "dodge") +
    xlab("Season") + scale_fill_discrete(name = "Weather Condition") +
    scale_x_discrete(breaks=1:4, label = c("Spring", "Summer", "Fall", "Winter"))
```


```{r}
time_label <- paste0(sprintf("%02d", 0:23), ":00 ", rep(c("AM", "PM"), each = 12))

train %>%
    group_by(year, hour, weathersit) %>%
    summarise(Count = sum(cnt)) %>%
    ggplot(aes(x = factor(hour), y = Count, fill = factor(weathersit))) + 
    geom_bar(stat = "identity", position = "dodge") +
    scale_x_discrete(breaks=c(0:23), label = time_label) +
    xlab("Hour") + scale_fill_discrete(name = "Weather Condition") +
    theme(axis.text.x = element_text(angle = 90))
```

```{r}
train %>%
    group_by(year, hour, workingday) %>%
    summarise(Count = sum(cnt)) %>%
    ggplot(aes(x = factor(hour), y = Count, fill = factor(workingday))) + 
    geom_bar(stat = "identity", position = "dodge") +
    xlab("Hour") + scale_fill_discrete(name = "Working Day") +
    scale_x_discrete(breaks=c(0:23), label = time_label) +
    theme(axis.text.x = element_text(angle = 90))
```

```{r}
gradient <- c("#1e139b", "#74c5a4", "#efea91", "#f6854d", "#9f0440")

train %>%
    filter(workingday == 1) %>%
    mutate(n.cnt = registered/(max(registered))) %>%
    ggplot(aes(x = hour, y = n.cnt, color = hum)) +
    geom_point(position = "jitter", size = 1, alpha = .7) +
    geom_jitter(width = .5, size = 1, alpha = .7) + 
    scale_color_gradientn(colors = gradient, name = "Humidity\n") +
    scale_x_continuous(breaks=c(0:23), label = time_label) + 
    theme(axis.text.x = element_text(angle = 90, face = "italic"),
          axis.text.y = element_text(face = "italic"), legend.position = "bottom",
          legend.title = element_text(size = 9, face = 'bold.italic')) +
    xlab("Hour") + ylab("Count")
```

```{r}
train %>%
    filter(workingday == 0) %>%
    mutate(n.cnt = registered/(max(registered))) %>%
    ggplot(aes(x = hour, y = n.cnt, color = hum)) +
    geom_point(position = "jitter", size = 1, alpha = .7) +
    geom_jitter(width = .5, size = 1, alpha = .7) + 
    scale_color_gradientn(colors = gradient, name = "Humidity\n") +
    scale_x_continuous(breaks=c(0:23), label = time_label) + 
    theme(axis.text.x = element_text(angle = 90), legend.position = "bottom",
          legend.title = element_text(size = 9, face = 'bold.italic')) +
    xlab("Hour") + ylab("Count")
```

```{r}
train %>%
    filter(workingday == 1) %>%
    mutate(n.cnt = casual/(max(casual))) %>%
    ggplot(aes(x = hour, y = n.cnt, color = hum)) +
    geom_point(position = "jitter", size = 1, alpha = .7) +
    geom_jitter(width = .5, size = 1, alpha = .7) + 
    scale_color_gradientn(colors = gradient, name = "Humidity\n") +
    scale_x_continuous(breaks=c(0:23), label = time_label) + 
    theme(axis.text.x = element_text(angle = 90, face = "italic"),
          axis.text.y = element_text(face = "italic"), legend.position = "bottom",
          legend.title = element_text(size = 9, face = 'bold.italic')) +
    xlab("Hour") + ylab("Count")
```

```{r}
train %>%
    filter(workingday == 0) %>%
    mutate(n.cnt = casual/(max(casual))) %>%
    ggplot(aes(x = hour, y = n.cnt, color = hum)) +
    geom_point(position = "jitter", size = 1, alpha = .7) +
    geom_jitter(width = .5, size = 1, alpha = .7) + 
    scale_color_gradientn(colors = gradient, name = "Humidity\n") +
    scale_x_continuous(breaks=c(0:23), label = time_label) + 
    theme(axis.text.x = element_text(angle = 90), legend.position = "bottom",
          legend.title = element_text(size = 9, face = 'bold.italic')) +
    xlab("Hour") + ylab("Count")
```

# Handle the data, again

```{r}
makePeak <- function(data){
    data <- data %>%
        mutate(peak = ifelse((workingday == 1 & (hour == 8 | (hour >= 17 & hour <= 18))) | ((workingday == 0 & (hour >= 10 & hour <= 19))), 1, 0))
}

train <- makePeak(train)
test <- makePeak(test)
```


# Modeling

```{r}
library(glmnet)

bikeCasual <- log(train$casual + 1)
bikeRegistered <- log(train$registered + 1)

newTrain <- train %>%
    select(-datetime, -weathersit, -season, -(casual:cnt))

newTest <- test %>%
    select(-datetime, -season, -weathersit)

newTrain$year <- factor(newTrain$year)
newTest$year <- factor(newTest$year)

newTrain$month <- factor(newTrain$month)
newTest$month <- factor(newTest$month)

newTrain$hour <- factor(newTrain$hour)
newTest$hour <- factor(newTest$hour)

train.matrix <- model.matrix(data = newTrain, object = ~.)
test.matrix <- model.matrix(data = newTest, object = ~.)
```

```{r}
doMC::registerDoMC(cores = 4)
lambda <- exp(-seq(8, 10, length.out = 400))

standard = TRUE
isLASSO = 1
family = 'gaussian'

set.seed(1)

cv.casual <- cv.glmnet(x = train.matrix, y = bikeCasual, nfolds = 10, lambda = lambda,
                       alpha = isLASSO, standardize = standard, parallel = TRUE, family = family)

cat("Cross Validaiton was completed.\n")
cat("Appropriate value of lambda :", cv.casual$lambda.min, "\n")
```

```{r}
set.seed(1)
cv.registered <- cv.glmnet(x = train.matrix, y = bikeRegistered, nfolds = 10, alpha = isLASSO,
                           lambda = lambda, standardize = standard, parallel = TRUE, family = family)

cat("Cross Validaiton was completed.\n")
cat("Appropriate value of lambda :", cv.registered$lambda.min, "\n")
```

```{r}
casual <- glmnet(x = train.matrix, y = bikeCasual, lambda = cv.casual$lambda.min,
                 alpha = isLASSO, standardize = standard)
casual.pred <- exp(as.numeric(predict(casual, test.matrix))) - 1
casual.pred[casual.pred < 0] = 0

cat("First Six Entries :", head(casual.pred))
```

```{r}
registered <- glmnet(x = train.matrix, y = bikeRegistered,
                     lambda = cv.registered$lambda.min, alpha = isLASSO, standardize = standard)
registered.pred <- exp(as.numeric(predict(registered, test.matrix))) - 1
registered.pred[registered.pred < 0] = 0

cnt.pred <- casual.pred + registered.pred

cat("First Six Entries :", head(registered.pred))
```

```{r}
submit.df <- data.frame(No = 1:length(cnt.pred), Count = cnt.pred)
write_csv(submit.df, "data/submit.csv")

# Score : 0.586186633218678
```