---
title: "Data Visualizing"
author: "Jaeyoon Han"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: pygments
    css: ~/Google Drive/ML Lecture/rmarkdown.css
---


```{r knitr_init, echo=FALSE, cache=FALSE, message = FALSE}
library(knitr)
library(rmdformats)
library(ggplot2)
library(MASS)
library(dplyr)

## Global options
knitr::opts_chunk$set(echo = TRUE, message = FALSE, prompt = FALSE,
                      tidy = TRUE, comment = NA, warning = FALSE, cache = TRUE,
                      fig.height = 4, fig.width = 7, fig.retina = 2,
                      fig.align = "center")
custom_theme <- theme_bw(base_family = "Ubuntu") +
        theme(legend.position = "right",
              axis.title.x = element_text(size = 11,
                                          margin = margin(10, 0, 0, 0),
                                          face = "bold"),
              axis.title.y = element_text(size = 11,
                                          margin = margin(0, 10, 0, 0),
                                          face = "bold"),
              plot.title = element_text(family = "Ubuntu", face = "bold"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.background = element_blank())
theme_set(custom_theme)
```

# 1. Bar Chart

```{r}
# 1. 막대그래프 ----------------------------------------------------------------
library(ggplot2)
library(gcookbook)
library(dplyr)

## 1. 
pgMean <- PlantGrowth %>%
        group_by(group) %>%
        summarise(weight = mean(weight))

pgMean

# 각 그룹별로 무게를 나타내보자.

ggplot(data = pgMean, aes(x = group, y = weight)) +
        geom_bar(stat = "identity")

## 2.

BOD # Time == 6 이 없다.
ggplot(BOD, aes(x = Time, y = demand)) +
        geom_bar(stat = "identity")

str(BOD)

ggplot(BOD, aes(x = factor(Time), y = demand)) +
        geom_bar(stat = "identity")

## 3.

cabbage_exp

ggplot(cabbage_exp, aes(x = Date, y = Weight, fill = Cultivar)) +
        geom_bar(stat = "identity")

ggplot(cabbage_exp, aes(x = Date, y = Weight, fill = Cultivar)) +
        geom_bar(stat = "identity", position = "dodge")


diamonds

ggplot(diamonds, aes(x = cut)) +
        geom_bar()

## 5.

uspopchange

data.frame(State = uspopchange$State, Rank = rank(uspopchange$Change))

upc <- uspopchange %>%
        filter(rank(Change) > 40)
upc

ggplot(upc, aes(x = Abb, y = Change, fill = Region)) + 
        geom_bar(stat = "identity")

## 6.

csub <- climate %>%
        filter(Source == "Berkeley" & Year >= 1900) %>%
        mutate(pos = Anomaly10y >= 0)

ggplot(csub, aes(x = Year, y = Anomaly10y)) + 
        geom_bar(stat = "identity", position = "identity")


ggplot(csub, aes(x = Year, y = Anomaly10y, fill = pos)) + 
        geom_bar(stat = "identity", position = "identity")

```

# 2. Line Graph

```{r}

# 2. 선 그래프 ----------------------------------------------------------------

## 1.

BOD

ggplot(BOD, aes(x = Time, y = demand)) + 
        geom_line()

ggplot(BOD, aes(x = factor(Time), y = demand, group = 1)) + 
        geom_line()

ggplot(BOD, aes(x = Time, y = demand)) + 
        geom_line() +
        ylim(0, max(BOD$demand))

ggplot(BOD, aes(x = Time, y = demand)) + 
        geom_line() + 
        geom_point()

## 2.

ToothGrowth

tg <- ToothGrowth %>%
        group_by(supp, dose) %>%
        summarise(length = mean(len))
tg

ggplot(tg, aes(x = dose, y = length, colour = supp)) +
        geom_line()

ggplot(tg, aes(x = dose, y = length, linetype = supp)) +
        geom_line()

# 실수하지 말 것 !
ggplot(tg, aes(x = dose, y = length)) +
        geom_line()

ggplot(tg, aes(x = dose, y = length, colour = supp)) + 
        geom_line(linetype = "dashed") + 
        geom_point(shape = 22, size = 3, fill = "white")

## 3.
head(uspopage)

ggplot(uspopage, aes(x = Year, y = Thousands, fill = AgeGroup)) + 
        geom_area()

ggplot(uspopage, aes(x = Year, y = Thousands, fill = AgeGroup)) +
        geom_area(colour = "black", size = .2, alpha = .4) + 
        scale_fill_brewer(palette="Blues", breaks = rev(levels(uspopage$AgeGroup)))
```

# 3. Scatter Plot

```{r}
# 1.
head(heightweight)

# 나이와 키 사이의 관계를 보고자 한다.
ggplot(data = heightweight, aes(x = ageYear, y = heightIn)) +
        geom_point()

ggplot(data = heightweight, aes(x = ageYear, y = heightIn)) + 
        geom_point(shape = 21)

# 성별에 따라서 색을 다르게 할 수 있다.
ggplot(data = heightweight, aes(x = ageYear, y = heightIn, colour = sex)) +
        geom_point() +
        geom_smooth(method = "lm")

ggplot(data = heightweight, aes(x = ageYear, y = heightIn, colour = sex, shape = sex)) + 
        geom_point() +
        geom_smooth(method = "lm")

# 몸무게가 높을 수록 색을 진하게 하거나, 점의 크기를 크게 할 수 있다.
ggplot(data = heightweight, aes(x = ageYear, y = heightIn, colour = weightLb)) +
        geom_point()

ggplot(data = heightweight, aes(x = ageYear, y = heightIn, size = weightLb)) + 
        geom_point()

ggplot(data = heightweight, aes(x = ageYear, y = heightIn, colour = weightLb, size = weightLb)) + 
        geom_point()

# 2.
data(diamonds)
tbl_df(diamonds)

ggplot(diamonds, aes(x = carat, y = price)) +
        geom_point()

# 점이 너무 많아서 보기가 힘들다. 그럴 땐
ggplot(diamonds, aes(x = carat, y = price)) +
        geom_point(alpha = .1)

ggplot(diamonds, aes(x = carat, y = price)) + 
        geom_point(alpha = .1, position = "jitter")

ggplot(diamonds, aes(x = carat, y = price, colour = color)) +
        geom_point(alpha = .2) +
        facet_wrap( ~ cut, nrow = 1)

# 3.
tbl_df(countries)

ctr <- countries %>%
        filter(Year == 2009, healthexp > 2000)
ctr

ggplot(data = ctr, aes(x = healthexp, y = infmortality)) +
        geom_point()

ggplot(data = ctr, aes(x = healthexp, y = infmortality)) +
        geom_point() +
        geom_text(aes(label = Name), size = 3, hjust = -.15)
```


# 4. Data Distribution

```{r}
# 1. Histogram

head(faithful)

ggplot(data = faithful, aes(x = waiting)) + 
        geom_histogram()

# stat_bin() 이 뭘까?
# bin : 뚜껑 달린 상자?

ggplot(data = faithful, aes(x = waiting)) + 
        geom_histogram(binwidth = 2)

### 실습
library(MASS)

head(birthwt) # 저체중아 출산 요소에 대한 데이터

# 산모의 흡연 여부로 나누기

ggplot(birthwt, aes(x = bwt)) +
        geom_histogram(fill = "white", colour = "black") + 
        facet_grid(smoke ~ .)

# Label이 0, 1로 나오는건 그닥 도움이 되지 않는다.

birthwt %>%
        mutate(smoke_label = ifelse(birthwt$smoke == 0, "No Smoke", "Smoke")) %>%
        ggplot(aes(x = bwt)) + 
        geom_histogram(fill = "white", colour = "black") +
        facet_grid(smoke_label ~ .)

ggplot(birthwt, aes(x = bwt, fill = factor(smoke))) + 
        geom_histogram(position = "identity", alpha = .4)

# 2. Density Curve

ggplot(faithful, aes(x = waiting)) + 
        geom_density()

ggplot(faithful, aes(x = waiting)) + 
        geom_line(stat = "density")

ggplot(faithful, aes(x = waiting, y = ..density..)) + 
        geom_histogram(fill = "cornsilk", colour = "grey60") +
        geom_density()

# 3. Box plot

ggplot(birthwt, aes(x = factor(race), y = bwt)) + 
        geom_boxplot()

ggplot(birthwt, aes(x = factor(race), y = bwt)) + 
        geom_boxplot(notch = TRUE)

ggplot(birthwt, aes(x = factor(race), y = bwt)) + 
        geom_boxplot() +
        stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "white")

# 4. Density 2D

ggplot(faithful, aes(x = eruptions, y = waiting)) +
        geom_point() +
        stat_density2d()

ggplot(faithful, aes(x = eruptions, y = waiting)) +
        geom_point() +
        stat_density2d(aes(colour = ..level..))

ggplot(faithful, aes(x = eruptions, y = waiting)) +
        stat_density2d(aes(fill = ..density..), geom = "raster", contour = FALSE)

ggplot(faithful, aes(x = eruptions, y = waiting)) +
        geom_point() +
        stat_density2d(aes(alpha = ..density..), geom = "tile", contour = FALSE)
```


# 5. Map

```{r}
# install.packages("maps")
library(maps)
library(mapproj)

states_map <- map_data("state")
ggplot(states_map, aes(x = long, y = lat, group = group)) +
        geom_polygon(fill = "white", colour = "black", size = .1)

world_map <- map_data("world")
east_asia <- map_data("world",
                      region = c("Japan", "China", "North Korea", "South Korea"))

ggplot(east_asia, aes(x = long, y = lat, group = group, fill = region)) + 
        geom_polygon(alpha = .5, colour = "black", size = .1)


# 실습
USArrests

crimes <- data.frame(state = tolower(rownames(USArrests)), USArrests)
crimes
head(states_map)

# 데이터를 합친다.
# crimes 데이터의 states 열과 states_map 데이터의 region 열을 기준으로 합친다.
crime_map <- left_join(states_map, crimes, by = c("region" = "state"))
head(crime_map)

crime_map <- crime_map %>%
        arrange(group, order)
head(crime_map)

ggplot(crime_map, aes(x = long, y = lat, group = group, fill = Assault)) + 
        geom_polygon(colour = "black", size = .1) + 
        coord_map("polyconic")

ggplot(crimes, aes(map_id = state, fill=Assault)) +
        geom_map(map = states_map, colour="black", size = .1) +
        scale_fill_gradient2(low = "#559999", mid = "grey90", high = "#BB650B",
                             midpoint = median(crimes$Assault)) +
        expand_limits(x = states_map$long, y = states_map$lat) +
        coord_map("polyconic")
```

